### ISSUE TITLE
No errors given for unauthorized 401

### ISSUE THREAD

**Issue by darrenparkinson** [jbogarin/go-cisco-webex-teams#1]
Hi Jose,

I was just using this SDK and I noticed that when I get a 401, I don't seem to get any indication of it so I'm unable to provide any feedback.  Is that something you might change?

Many thanks,
Darren.

**Comment by jbogarin** [comment]
Darren,

Every call returns a resty.Response object. You can get the HTTP StatusCode using something like:

```golang
newRoom, response, err := Client.Rooms.CreateRoom(roomRequest)
response.StatusCode()
```

Is that good enough or are you looking for something else?

**Comment by darrenparkinson** [comment]
Ah sorry about that. I should have realised. Really sorry. Does resty provide much extra over the net/http library?

**Comment by jbogarin** [comment]
Honestly, not really sure if it provides extra info or not. I used it because it was easier to make the requests, however at the end of the day, I think you can still access the net/http info if you need it.
