### ISSUE TITLE
Addition of Events endpoints

### ISSUE THREAD

**Issue by darrenparkinson** [jbogarin/go-cisco-webex-teams#15]
Hi @jbogarin hope you're well.  I'm just logging this issue to see if you have any plans to add the events endpoints:

https://developer.webex.com/docs/api/v1/events

Many thanks,
D.

**Comment by jbogarin** [comment]
I have code that autogenerates the SDK with an OpenAPI spec. So, I'll work on creating the spec for those endpoints and generate the code.

I'm super busy these next few weeks, so I'll probably get to it in about two weeks.

**Comment by darrenparkinson** [comment]
Great stuff, thanks.  That process sounds interesting -- would be great to catch up on that at some point.

**Comment by jbogarin** [comment]
I already included the events API. I also added the openapi.yaml file, so if you need a new endpoint in the future, it could be easier to added the openapi spec and I can generate the SDK from there.

**Comment by darrenparkinson** [comment]
> I have code that autogenerates the SDK with an OpenAPI spec. So, I'll work on creating the spec for those endpoints and generate the code.

Do you have any details on this that you wouldn't mind sharing?
