### ISSUE TITLE
New tag required?

### ISSUE THREAD

**Issue by darrenparkinson** [jbogarin/go-cisco-webex-teams#17]
Hi, 

I just wanted to check that this library is still being maintained?  There appears to be 18 commits since the 0.4.0 tag and I wondered if you'd be able to create a new version with the latest commits?

Thanks.

**Comment by jbogarin** [comment]
It's being maintained, but honestly, with a very low priority. I've been focused on DNAC libraries (Python, Go, Ansible, and Terraform) and other work-related stuff.

Let me remember what was the last thing I did and create a new tag.

**Comment by jbogarin** [comment]
I created tag 0.4.1 with events and audit events api
