### ISSUE TITLE
Failed to get one on one conversation

### ISSUE THREAD

**Issue by Verzu23** [jbogarin/go-cisco-webex-teams#21]
`"message":"Failed to get one on one conversation","errors":[{"description":"Failed to get one on one conversation"}`

```GO
markDownMessage := &webexteams.MessageCreateRequest{
		Markdown:      "MESSAGE",
		ToPersonEmail: "MY EMAIL",
	}
	_, rep, err := Client.Messages.CreateMessage(markDownMessage)
	if err != nil {
		fmt.Println(err.Error())
	}
```
Whats going on here ? 
If i make manually the request it works...
Can you help me?

**Comment by jbogarin** [comment]
I've never seen that error. Can you send the API request you are doing in curl, postman or something like that?

**Comment by Verzu23** [comment]
In Postman I set URL: https://webexapis.com/v1/messages
Set Header Authorization: Bearer TOKEN
Set body:
- Markdown : MESSAGE
- ToPersonEmail : EMAIL

And it works as expected

With the library seems execute the same header and body but probably there's something different...

**Comment by jbogarin** [comment]
I just tested this and it works:
```go
package main
import (
        "fmt"
        "log"
        webexteams "github.com/jbogarin/go-cisco-webex-teams/sdk"
)
var Client *webexteams.Client

func main() {
        Client = webexteams.NewClient()
        markDownMessage := &webexteams.MessageCreateRequest{
                Markdown: "This is a markdown message. *Italic*, **bold** and ***italic/bold***.",
                ToPersonEmail: "blurr@webex.bot",
        }
        newMarkDownMessage, _, err := Client.Messages.CreateMessage(markDownMessage)
        if err != nil {
                log.Fatal(err)
        }
        fmt.Println("POST:", newMarkDownMessage.ID, newMarkDownMessage.Markdown, newMarkDownMessage.Created)
}

**Comment by Verzu23** [comment]
The only difference between your code and mine is that I add 
```GO
Client = webexteams.NewClient()
Client.SetAuthToken("<WEBEX TEAMS TOKEN>")
....
```

just before

**Comment by jbogarin** [comment]
That also worked for me.

**Comment by Verzu23** [comment]
Okk I'll check it out tomorrow and let you know if I figure out something
Thanks
