### ISSUE TITLE
Error loading module requirements gopkg.in/resty.v1

### ISSUE THREAD

**Issue by darrenparkinson** [jbogarin/go-cisco-webex-teams#6]
Hi,

Just trying to use the new version and I'm getting the following error, any thoughts?

```
go: github.com/go-resty/resty@v1.12.0: parsing go.mod: unexpected module path "gopkg.in/resty.v1"
go: error loading module requirements
```

Essentially I just created a new repo, used `go get` to get resty v2.0.0 and go-cisco-webex-teams v0.2.0, created a basic main.go using the library and I get the error.

main.go:

```
package main

import (
	"github.com/go-resty/resty/v2"
	webexteams "github.com/jbogarin/go-cisco-webex-teams/sdk"
)

var Client *webexteams.Client

func main() {
	client := resty.New()
	token := "" 
	client.SetAuthToken(token)
	Client = webexteams.NewClient(client)

}
```

Thanks.

**Comment by jbogarin** [comment]
The import for resty should be

> "github.com/go-resty/resty"

I'm going to update that on the examples.

**Comment by jbogarin** [comment]
I updated the examples to reflect the change. Sorry for the trouble and delay.
