### ISSUE TITLE
Unable to list messages

### ISSUE THREAD

**Issue by hallyn** [jbogarin/go-cisco-webex-teams#9]
Hi,

I'm able to send a message to a space, but cannot get listmessages (for the same space) to work:

```
messages &{[]} resp {"message":"Failed to get activity.","errors":[{"description":"Failed to get activity."}],"trackingId":"ROUTER_..."} err <nil>
```

Code is:
```
        Client = webexteams.NewClient()
        messageQueryParams := &webexteams.ListMessagesQueryParams{
                RoomID: room.webexRoomID,
                Max: 5,
        }
        messages, resp, err := Client.Messages.ListMessages(messageQueryParams)
        fmt.Printf("messages %v resp %v err %v\n", messages, resp, err)
        if err != nil {
                log.Fatal(err)
        }
        for id, message := range messages.Items {
                fmt.Println("GET:", id, message.ID, message.Text, message.Created)
        }
```

Is this due to an api change, or am I doing it wrong?

**Comment by hallyn** [comment]
Hm, right, I think I knew this a few months ago:

https://stackoverflow.com/questions/50156249/cisco-spark-failed-to-get-activity-when-retrieving-messages-as-a-bot

But it's a weird error, and I was really hoping this was fixed by now.

**Comment by jbogarin** [comment]
Are you using a bot token?

**Comment by hallyn** [comment]
Yes.

**Comment by jbogarin** [comment]
Bots cannot list messages in a space, they can only get their own messages. I'm closing this issue.

**Comment by hallyn** [comment]
Ok, thanks for verifying that.  It is though a huge limitation that I was hoping would one day be fixed.  These are the sorts of limitations that make people choose another platform.
